@base_url = http://localhost:3000/api

POST {{base_url}}/users/ HTTP/1.1
Content-Type: application/json

{
    "name": "test-user",
    "username": "tester",
    "email": "test@test.com",
    "password": "123456"
}

###

DELETE {{base_url}}/users/5eef676222bc473e75ee8c2f
