@base_url = http://localhost:3000/api/videos

### 
//watch a video - get('/:videoId', getVideo)
GET {{base_url}}/5ef63ee15863d10ca4530089 HTTP/1.1

###
GET {{base_url}}/techs/5ef6117d291db8ed03313e3b HTTP/1.1

###
//list videos by level - get('/level/:level', listVideosByLevel)
GET {{base_url}}/level/newbie HTTP/1.1

###
// list video comments - get('/:videoId/comments', listVideoComments)
GET {{base_url}}/5ef63ee15863d10ca4530089/comments HTTP/1.1

### 
//create a video - post('/me', uploadVideo)
POST {{base_url}}/me HTTP/1.1
Content-Type: application/json

{
  "title": "alberto video 3",
  "description": "es un test",
  "duration": 20,
  "level": "newbie"
}
### 
//add a video comment - post('/me/:videoId/comments', addVideoComment)
POST {{base_url}}/me/5ef63ee15863d10ca4530089/comments HTTP/1.1
Content-Type: application/json

{
  "userId": "5ef63e7b5863d10ca4530088",
  "text": "alb comment test 3"
}

### 
//edit video info - put('/me/:videoId', editVideoInfo)
PUT {{base_url}}/me/5ef63ee15863d10ca4530089 HTTP/1.1
Content-Type: application/json

{
  "title": "alberto video 1 ahora es video 2",
  "duration": 25
}

### 
//edit video comment - put('/me/:videoId/comments/:commentId', editVideoComment)
PUT {{base_url}}/me/5ef63ee15863d10ca4530089/comments/5ef641cfe989560edf1cf361 HTTP/1.1
Content-Type: application/json

{
  "text": "editando comment test 2"
}

### 
//delete a video - delete('/me/:videoId', deleteVideo)
DELETE {{base_url}}/me/5ef640fc95776e0e6b9c3aa7 HTTP/1.1

### 
//delete video comment - delete('/me/:videoId/comments/:commentId', deleteVideoComment)
DELETE {{base_url}}/me/5ef63ee15863d10ca4530089/comments/5ef649c2f217a7173e5c700c HTTP/1.1

// CHECKING USER ROUTES

### 
GET {{base_url}}/ HTTP/1.1

###
GET {{base_url}}/techs/121 HTTP/1.1

###
GET {{base_url}}/level/121 HTTP/1.1

###
GET {{base_url}}/search/1212 HTTP/1.1

###
GET {{base_url}}/12132/comments HTTP/1.1

###
POST {{base_url}}/me HTTP/1.1
###
POST {{base_url}}/me/1213/comments HTTP/1.1
###
PUT {{base_url}}/me/12134 HTTP/1.1
###
PUT {{base_url}}/me/likes HTTP/1.1
###
PUT {{base_url}}/me/views HTTP/1.1
###
PUT {{base_url}}/me/4432/comments/2343 HTTP/1.1
###
DELETE {{base_url}}/me/12134 HTTP/1.1
###
DELETE {{base_url}}/me/4432/comments/2343 HTTP/1.1
