@base_url = http://localhost:3000/api/videos

###
//watch a video - get('/:videoId', getVideo)
GET {{base_url}}/5ef61fb985def66d8f6b2143 HTTP/1.1

###
GET {{base_url}}/techs/5ef6117d291db8ed03313e3b HTTP/1.1

###
//list videos by level - get('/level/:level', listVideosByLevel)
GET {{base_url}}/level/newbie HTTP/1.1

###
// list video comments - get('/:videoId/comments', listVideoComments)
GET {{base_url}}/5ef61fb985def66d8f6b2143/comments HTTP/1.1

###
//create a video - post('/me', uploadVideo)
POST {{base_url}}/me HTTP/1.1
Content-Type: application/json

{
  "title": "Sabado test!",
  "description": "es un test",
  "duration": 20,
  "level": "newbie"
}
###
//add a video comment - post('/me/:videoId/comments', addVideoComment)
POST {{base_url}}/me/5ef63ee15863d10ca4530089/comments HTTP/1.1
Content-Type: application/json

{
  "userId": "5ef63e7b5863d10ca4530088",
  "text": "alb comment test 3"
}

###
//edit video info - put('/me/:videoId', editVideoInfo)
PUT {{base_url}}/me/5ef63ee15863d10ca4530089 HTTP/1.1
Content-Type: application/json

{
  "title": "alberto video 1 ahora es video 2",
  "duration": 25
}

###
//edit video comment - put('/me/:videoId/comments/:commentId', editVideoComment)
PUT {{base_url}}/me/5ef61fb985def66d8f6b2143/comments/5ef6304455448b76c8b7ac73 HTTP/1.1
Content-Type: application/json

{
  "text": "editando comment test"
}
###
//increase video views - put('/:videoId/views', increaseVideoViews)
PUT {{base_url}}/5ef61fb985def66d8f6b2143/views HTTP/1.1

###
//increase video likes - put('/me/:videoId/likes', increaseVideoLike)
PUT {{base_url}}/me/5ef61fb985def66d8f6b2143/likes HTTP/1.1
Content-Type: application/json

{
  "userId": "5ef60862f4c9e84fe1a60f3f"
}

###
//delete a video - delete('/me/:videoId', deleteVideo)
DELETE {{base_url}}/me/5ef7023d612e1884aaa6e667 HTTP/1.1

###
//delete video comment - delete('/me/:videoId/comments/:commentId', deleteVideoComment)
DELETE {{base_url}}/me/5ef61fb985def66d8f6b2143/comments/5ef62fcb55448b76c8b7ac71 HTTP/1.1

// CHECKING USER ROUTES

###
GET {{base_url}}/ HTTP/1.1

###
GET {{base_url}}/techs/121 HTTP/1.1

###
GET {{base_url}}/level/121 HTTP/1.1

###
GET {{base_url}}/search/1212 HTTP/1.1

###
GET {{base_url}}/12132/comments HTTP/1.1

###
POST {{base_url}}/me HTTP/1.1
###
POST {{base_url}}/me/1213/comments HTTP/1.1
###
PUT {{base_url}}/me/12134 HTTP/1.1
###
PUT {{base_url}}/me/likes HTTP/1.1
###
PUT {{base_url}}/me/views HTTP/1.1
###
PUT {{base_url}}/me/4432/comments/2343 HTTP/1.1
###
DELETE {{base_url}}/me/12134 HTTP/1.1
###
DELETE {{base_url}}/me/4432/comments/2343 HTTP/1.1
